#! /usr/bin/env bash
# Generated by configuration script

# 'strict' mode in bash
set -euo pipefail

cd "/opt/steam/steamapps/common/DontStarveTogether/bin"
shared_params=("./dontstarve_dedicated_server_nullrenderer")
shared_params+=(-cluster "kfs1")
shared_params+=(-persistent_storage_root "/opt/steam/steamapps/common/DontStarveTogether")
shared_params+=(-config_dir "Servers")
shared_params+=(-monitor_parent_process $$)

set -x
"${shared_params[@]}" -shard "Caves" | sed "s:^:[kfs1.Caves] :" &
"${shared_params[@]}" -shard "Overworld" | sed "s:^:[kfs1.Overworld] :" &
set +x

wait
